# Generated by Django 2.2.4 on 2019-08-04 09:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0002_auto_20190804_1216'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradata',
            name='gender',
            field=models.CharField(max_length=20),
        ),
        migrations.DeleteModel(
            name='Gender',
        ),
    ]
