# Generated by Django 2.2.4 on 2019-08-04 12:05

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('user_auth', '0003_auto_20190804_1237'),
    ]

    operations = [
        migrations.AlterField(
            model_name='extradata',
            name='gender',
            field=models.CharField(choices=[('male', 'Male'), ('female', 'Female'), ('other', 'Other')], max_length=20),
        ),
    ]
