# Generated by Django 2.2.4 on 2019-08-05 13:59

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='amount',
            field=models.PositiveIntegerField(blank=True, default=0),
        ),
        migrations.AlterField(
            model_name='books',
            name='year',
            field=models.PositiveIntegerField(),
        ),
    ]
