# Generated by Django 2.2.4 on 2019-08-06 06:19

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0001_initial'),
    ]

    operations = [
        migrations.AlterUniqueTogether(
            name='orderedbook',
            unique_together={('order', 'book', 'price')},
        ),
    ]
