# Generated by Django 2.2.4 on 2019-08-06 11:35

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0002_auto_20190806_0919'),
    ]

    operations = [
        migrations.AlterField(
            model_name='orderedbook',
            name='book',
            field=models.ForeignKey(on_delete=django.db.models.deletion.PROTECT, to='storefront.Books'),
        ),
    ]
