# Generated by Django 2.2.4 on 2019-08-05 15:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0003_orders_active'),
    ]

    operations = [
        migrations.RenameField(
            model_name='orders',
            old_name='active',
            new_name='is_active',
        ),
    ]
