# Generated by Django 2.2.4 on 2019-08-14 15:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('storefront', '0005_auto_20190809_1333'),
    ]

    operations = [
        migrations.AlterField(
            model_name='books',
            name='author',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
        migrations.AlterField(
            model_name='books',
            name='genre',
            field=models.CharField(blank=True, max_length=100, null=True),
        ),
    ]
